#!/bin/bash

{
    printf "Version:\n";
    node -p "require('./package.json').version";

    printf "\nMode:\n";
    echo "${SKYNET_MYSKY_ENV:-production}";

    printf "\nBranch:\n";
    git describe --all --long;

    printf "\nLocal links:\n";
    npm ls --depth=0 --link=true;
} > dist/version.txt
