#!/bin/bash

# Clear dist folder, copy over HTML and assets.
npx rimraf dist &&
cp -R html dist &&
cp -R assets dist/assets &&

# Run all webpack scripts.
printf "\nBuilding src..." &&
npx webpack &&
printf "\nBuilding scripts..." &&
npx webpack --config webpack.config.scripts.js &&

# Minify the HTML files and inline assets.
node utilities/minify-src.js dist/*.html &&
# Delete unneeded assets.
rm dist/main.js dist/seed-display.js dist/seed-selection.js dist/permissions-display.js dist/ui.js &&
find dist -name "*.css" -type f -delete &&

# Generate version file.
./utilities/generate_versions_file
